name: vuepress-deploy

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Vuepress deploy
        uses: jenkey2011/vuepress-deploy@v1.8.1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: pnpm install && pnpm docs:build # This is the command that builds your Vuepress site
          BUILD_DIR: src/.vuepress/dist/ # This is the directory where the built files are located
      - name: Deploy site to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          token: ${{ secrets.DENO_TOKEN }}
          project_id: ${{ secrets.DENO_PROJECT }}
          entrypoint: public/index.html
