name: vuepress-deploy

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  deno-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Allows authentication with Deno Deploy.
      contents: read # Allows cloning the repo.
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # choose pnpm version to use
          version: 7
          # install deps with pnpm
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # choose node.js version to use
          node-version: 18
          # cache deps for pnpm
          cache: pnpm
      # run build script
      - name: Build VuePress site
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm docs:build
        #build_dir: src/.vuepress/dist/ # This is the directory where the built files are located
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: nfway-vuepress-next-test # the name of the project on Deno Deploy
          entrypoint: https://deno.land/std/http/file_server.ts
          root: src/.vuepress/public # Where the built HTML/CSS/JS files are located.
