name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install && npm ci

      - name: Build site
        run: npm run docs:build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl-action@v0.3.3
        with:
          cmd: "deploy"
          args: "--no-check ./path/to/your/site/folder ${{ secrets.DENO_DEPLOY_TOKEN }}"
