name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run vuepress build src

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: nfway-vuepress-next-test # the name of the project on Deno Deploy
          entrypoint: ./main.ts # the entrypoint to deploy
          args: "--no-check --reload --allow-read=./src/.vuepress/dist"
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
