name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install && npm ci

      - name: Build site
        run: npm run docs:build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "nfway-vuepress-next-test"
          entrypoint: "./main.ts" # TODO: update entrypoint
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
